// SPDX-License-Identifier: BUSL-1.1
pragma solidity ^0.8.26;

import "../TychoRouterTestSetup.sol";
import {CommonBase} from "../../lib/forge-std/src/Base.sol";
import {Constants} from "../Constants.sol";
import {RestrictTransferFrom} from "../../src/RestrictTransferFrom.sol";
import {
    RocketpoolExecutor,
    RocketpoolExecutor__InvalidDataLength,
    IRocketTokenRETH
} from "../../src/executors/RocketpoolExecutor.sol";
import {StdAssertions} from "../../lib/forge-std/src/StdAssertions.sol";
import {StdChains} from "../../lib/forge-std/src/StdChains.sol";
import {StdCheats, StdCheatsSafe} from "../../lib/forge-std/src/StdCheats.sol";
import {StdUtils} from "../../lib/forge-std/src/StdUtils.sol";
import {TestUtils} from "../TestUtils.sol";

contract RocketpoolExecutorExposed is RocketpoolExecutor {
    constructor(address _rocketDepositPool, address _permit2)
        RocketpoolExecutor(_rocketDepositPool, _permit2)
    {}

    function decodeParams(bytes calldata data)
        external
        pure
        returns (
            bool isDeposit,
            RestrictTransferFrom.TransferType transferType,
            address receiver
        )
    {
        return _decodeData(data);
    }
}

contract RocketpoolExecutorTest is TestUtils, Constants {
    RocketpoolExecutorExposed rocketpoolExecutor;

    // v1.4 (Saturn 1) deposit pool
    address constant ROCKET_DEPOSIT_POOL =
        0xCE15294273CFb9D9b628F4D61636623decDF4fdC;

    modifier setUpFork(uint256 blockNumber) {
        vm.createSelectFork(vm.rpcUrl("mainnet"), blockNumber);
        rocketpoolExecutor =
            new RocketpoolExecutorExposed(ROCKET_DEPOSIT_POOL, PERMIT2_ADDRESS);
        _;
    }

    function setUp() public setUpFork(24480104) {}

    function testDecodeParams() public view {
        bytes memory params = abi.encodePacked(
            uint8(1), // isDeposit = true
            RestrictTransferFrom.TransferType.Transfer,
            BOB
        );

        (
            bool isDeposit,
            RestrictTransferFrom.TransferType transferType,
            address receiver
        ) = rocketpoolExecutor.decodeParams(params);

        assertTrue(isDeposit);
        assertEq(
            uint8(transferType),
            uint8(RestrictTransferFrom.TransferType.Transfer)
        );
        assertEq(receiver, BOB);
    }

    function testDecodeParamsBurn() public view {
        bytes memory params = abi.encodePacked(
            uint8(0), // isDeposit = false (burn)
            RestrictTransferFrom.TransferType.Transfer,
            ALICE
        );

        (
            bool isDeposit,
            RestrictTransferFrom.TransferType transferType,
            address receiver
        ) = rocketpoolExecutor.decodeParams(params);

        assertFalse(isDeposit);
        assertEq(
            uint8(transferType),
            uint8(RestrictTransferFrom.TransferType.Transfer)
        );
        assertEq(receiver, ALICE);
    }

    function testDecodeParamsInvalidDataLength() public {
        bytes memory invalidParams = abi.encodePacked(uint8(1), BOB);

        vm.expectRevert(RocketpoolExecutor__InvalidDataLength.selector);
        rocketpoolExecutor.decodeParams(invalidParams);
    }

    /// Test deposit
    /// Tx 0xe0f1db165b621cb1e50b629af9d47e064be464fbcc7f2bcba3df1d27dbb916be at block 24480105
    /// User deposited 85 ETH and received 73382345660413064855 rETH (0.05% fee)
    function testSwapDeposit() public setUpFork(24480104) {
        IRocketTokenRETH RETH = IRocketTokenRETH(RETH_ADDR);
        uint256 amountIn = 85 ether;
        bytes memory protocolData = abi.encodePacked(
            uint8(1), // isDeposit = true
            RestrictTransferFrom.TransferType.Transfer,
            BOB
        );

        vm.deal(address(rocketpoolExecutor), amountIn);

        uint256 rethBalanceBefore = RETH.balanceOf(BOB);
        uint256 amountOut = rocketpoolExecutor.swap(amountIn, protocolData);
        uint256 rethBalanceAfter = RETH.balanceOf(BOB);

        assertEq(rethBalanceAfter - rethBalanceBefore, amountOut);
        assertEq(amountOut, 73_382_345_660_413_064_855);
    }

    /// Test burn
    /// Block 24481338: user burned 2515686112138065226 rETH and received 2912504376202664754 ETH
    function testSwapBurn() public setUpFork(24481337) {
        uint256 amountIn = 2_515_686_112_138_065_226;
        bytes memory protocolData = abi.encodePacked(
            uint8(0), // isDeposit = false (burn)
            RestrictTransferFrom.TransferType.Transfer,
            BOB
        );

        deal(RETH_ADDR, address(rocketpoolExecutor), amountIn);

        uint256 ethBalanceBefore = BOB.balance;
        uint256 amountOut = rocketpoolExecutor.swap(amountIn, protocolData);
        uint256 ethBalanceAfter = BOB.balance;

        assertEq(ethBalanceAfter - ethBalanceBefore, amountOut);
        assertEq(amountOut, 2_912_504_376_202_664_754);
    }

    function testDecodeDepositIntegration() public view {
        // Generated by the SwapEncoder - test_encode_rocketpool
        bytes memory protocolData =
            loadCallDataFromFile("test_encode_rocketpool_deposit");

        (
            bool isDeposit,
            RestrictTransferFrom.TransferType transferType,
            address receiver
        ) = rocketpoolExecutor.decodeParams(protocolData);

        assertTrue(isDeposit);
        assertEq(
            uint8(transferType),
            uint8(RestrictTransferFrom.TransferType.Transfer)
        );
        assertEq(receiver, BOB);
    }

    function testDecodeBurnIntegration() public view {
        // Generated by the SwapEncoder - test_encode_rocketpool
        bytes memory protocolData =
            loadCallDataFromFile("test_encode_rocketpool_burn");

        (
            bool isDeposit,
            RestrictTransferFrom.TransferType transferType,
            address receiver
        ) = rocketpoolExecutor.decodeParams(protocolData);

        assertFalse(isDeposit);
        assertEq(
            uint8(transferType),
            uint8(RestrictTransferFrom.TransferType.Transfer)
        );
        assertEq(receiver, BOB);
    }

    /// Integration test for deposit encoding (uses calldata generated by Rust SwapEncoder)
    /// Tx 0xe0f1db165b621cb1e50b629af9d47e064be464fbcc7f2bcba3df1d27dbb916be at block 24480105
    /// User deposited 85 ETH and received 73382345660413064855 rETH
    function testSwapDepositIntegration() public setUpFork(24480104) {
        IRocketTokenRETH RETH = IRocketTokenRETH(RETH_ADDR);
        bytes memory protocolData =
            loadCallDataFromFile("test_encode_rocketpool_deposit");

        uint256 amountIn = 85 ether;

        vm.deal(address(rocketpoolExecutor), amountIn);

        uint256 rethBalanceBefore = RETH.balanceOf(BOB);
        uint256 amountOut = rocketpoolExecutor.swap(amountIn, protocolData);
        uint256 rethBalanceAfter = RETH.balanceOf(BOB);

        assertEq(rethBalanceAfter - rethBalanceBefore, amountOut);
        assertEq(amountOut, 73_382_345_660_413_064_855);
    }

    /// Integration test for burn encoding (uses calldata generated by Rust SwapEncoder)
    /// Block 24481338: user burned 2515686112138065226 rETH and received 2912504376202664754 ETH
    function testSwapBurnIntegration() public setUpFork(24481337) {
        bytes memory protocolData =
            loadCallDataFromFile("test_encode_rocketpool_burn");

        uint256 amountIn = 2_515_686_112_138_065_226;

        deal(RETH_ADDR, address(rocketpoolExecutor), amountIn);

        uint256 ethBalanceBefore = BOB.balance;
        uint256 amountOut = rocketpoolExecutor.swap(amountIn, protocolData);
        uint256 ethBalanceAfter = BOB.balance;

        assertEq(ethBalanceAfter - ethBalanceBefore, amountOut);
        assertEq(amountOut, 2_912_504_376_202_664_754);
    }

    function testExportContract() public {
        exportRuntimeBytecode(address(rocketpoolExecutor), "Rocketpool");
    }
}

// Rocketpool deposit and burn tests are separated into different contracts because they
// require different fork blocks to test against real historical transactions.

/// @notice Tests Rocketpool deposit (ETH -> rETH) via TychoRouter
/// Tx 0xe0f1db165b621cb1e50b629af9d47e064be464fbcc7f2bcba3df1d27dbb916be at block 24480105
contract RocketpoolDepositTest is TychoRouterTestSetup {
    function getForkBlock() public pure override returns (uint256) {
        return 24480104;
    }

    function testSingleSwap() public {
        IRocketTokenRETH RETH = IRocketTokenRETH(RETH_ADDR);

        uint256 amountIn = 85 ether;
        bytes memory callData = loadCallDataFromFile(
            "test_single_encoding_strategy_rocketpool_deposit"
        );

        // Fund ALICE with ETH to send with the call
        vm.deal(ALICE, amountIn);

        vm.startPrank(ALICE);

        uint256 rethBalanceBefore = RETH.balanceOf(ALICE);
        (bool success,) = tychoRouterAddr.call{value: amountIn}(callData);
        uint256 rethBalanceAfter = RETH.balanceOf(ALICE);

        // Check balances
        assertTrue(success, "Call Failed");
        assertEq(
            rethBalanceAfter - rethBalanceBefore, 73_382_345_660_413_064_855
        );
        assertEq(RETH.balanceOf(tychoRouterAddr), 0);
        assertEq(tychoRouterAddr.balance, 0);
    }
}

/// @notice Tests Rocketpool burn (rETH -> ETH) via TychoRouter
/// Block 24481338: user burned 2515686112138065226 rETH
contract RocketpoolBurnTest is TychoRouterTestSetup {
    function getForkBlock() public pure override returns (uint256) {
        return 24481337;
    }

    function testSingleSwap() public {
        IRocketTokenRETH RETH = IRocketTokenRETH(RETH_ADDR);

        uint256 amountIn = 2_515_686_112_138_065_226;
        bytes memory callData = loadCallDataFromFile(
            "test_single_encoding_strategy_rocketpool_burn"
        );

        // Fund BOB with rETH to send with the call
        deal(RETH_ADDR, BOB, amountIn);

        vm.startPrank(BOB);

        RETH.approve(tychoRouterAddr, type(uint256).max);

        uint256 ethBalanceBefore = BOB.balance;
        (bool success,) = tychoRouterAddr.call(callData);
        uint256 ethBalanceAfter = BOB.balance;

        // Check balances
        assertTrue(success, "Call Failed");
        assertEq(ethBalanceAfter - ethBalanceBefore, 2_912_504_376_202_664_754);
        assertEq(RETH.balanceOf(tychoRouterAddr), 0);
        assertEq(tychoRouterAddr.balance, 0);
    }
}
