name: Slither Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive
      - uses: crytic/slither-action@f197989dea5b53e986d0f88c60a034ddd77ec9a8
        with:
          target: 'foundry/'
          slither-args: '--filter-paths foundry/lib/'